version: '3.8'

services:
    db:
      image: postgres:16.1
      container_name: db-companies
      restart: always
      volumes:
        - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
        - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      environment:
        POSTGRES_DB: 'productos'
        POSTGRES_USER: 'laboratory'
        POSTGRES_PASSWORD: '1q2w3e4r'
      ports:
        - '5432:5432'